version: '3.7'
services:
    jupyterlab:
        image: ai2ys/jupyterlab:covid19eda
        container_name: covid19_eda
        user: $USER
        working_dir: /workspace    
        build:
            context: .
            dockerfile: dockerfile
            args: 
                - USER_NAME=$USER
        ports:
            - "8888:8888"
        volumes:
            - ../:/workspace
        environment: 
            - USER=$USER